- name: Destroy Redmine containers
  hosts: webservers
  gather_facts: no
  become: true

  tasks:
    - name: Stop and remove Redmine container
      community.docker.docker_container:
        name: redmine
        state: absent
        force_kill: true
      ignore_errors: true
